
const fonts = [
  'Abril Fatface',
  'Arapey',
  'Asset',  
  'Barrio',
  'Bellefair',
  'Bigelow Rules',
  'Bodoni Moda',
  'Borel',
  'Bungee Shade',
  'Butcherman',
  'Caesar Dressing',
  'Charm',
  'Chicle',
  'Cormorant',
  'Courier Prime',
  'Diplomata',
  'Eagle Lake',
  'Fascinate Inline',
  'Frijole',
  'Gravitas One',
  'Halant',
  'Holtwood One SC',
  'Imbue',
  'Jacques Francois Shadow',
  'Katibeh',
  'Kumar One',
  'Kumar One Outline',
  'New Amsterdam',
  'New Rocker',
  'Permanent Marker',
  'Playfair Display',
  'Protest Guerrilla',
  'Rancho',
  'Rye',
  'Sigmar One',
  'Single Day',
  'Snowburst One',
  'Special Elite',
  'Ultra',
  'Viaoda Libre',
  'Yuji Syuku'
];

export default fonts;